
version: '3.8'

services:
  auto-ria-project-postgres:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-auto-ria-project}'
    volumes:
      - ./auto-ria-project-api-db:/var/lib/postgresql/auto-ria-project

  auto-ria-project-redis:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-redispass}'
    restart: unless-stopped

  auto-ria-project-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "8000:9000"
      - "8001:9001"
    volumes:
      - ./auto-ria-project-api-s3-data:/usr/src/app/s3
    environment:
      MINIO_ROOT_USER:          # AWS_S3_ACCESS_KEY
      MINIO_ROOT_PASSWORD:    # AWS_S3_SECRET_KEY

volumes:
  auto-ria-project-api-db:
  auto-ria-project-api-s3:
